version: '3'
services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py

  airflow:
    image: apache/airflow:2.0.1
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
